[versions]
agp = "8.10.1"
kotlin = "1.9.24"
api = "82"
dexkit = "2.0.5"

[libraries]
api = { group = "de.robv.android.xposed", name = "api", version.ref = "api" }
dexkit = { group = "org.luckypray", name = "dexkit", version.ref = "dexkit" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

