name: Android CI
 
on:
  push:
    branches: [ "android" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Debug
      run: ./gradlew :myapplication:assembleDebug

    - name: Sign APK
      run: |
        echo "${{ secrets.SIGN_KEY }}" | base64 --decode > debug.keystore
        keytool -list -v -keystore debug.keystore -alias androiddebugkey -storepass android
        apksigner sign --ks debug.keystore --ks-pass -pass:android --v3-signing-enabled false app/build/outputs/apk/debug/*.apk

    - name: Upload a Debug Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ci-debug-apk
        path: app/build/outputs/apk/debug
