name: Android CI
 
on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Decode Keystore
      run: |
        mkdir -p ~/.android
        echo "${{ secrets.SIGN_KEY }}" | base64 --decode > ~/.android/debug.keystore

    - name: Verify Debug Keystore
      run: keytool -list -v -keystore ~/.android/debug.keystore -alias androiddebugkey -storepass android

    - name: Build Debug
      run: ./gradlew :myapplication:assembleDebug

    - name: Verify Debug Keystore 2
      run: keytool -list -v -keystore ~/.android/debug.keystore -alias androiddebugkey -storepass android

    - name: Upload a Debug Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ci-debug-apk
        path: app/build/outputs/apk/debug
