name: AutoBuild

on:
  watch:
    types: [started]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch latest wsl kernel source
        run: git clone https://github.com/microsoft/WSL2-Linux-Kernel -b linux-msft-wsl-5.10.y --depth 1 .

      - name: Install build tool chain
        run: sudo apt update && sudo apt install build-essential flex bison libssl-dev libelf-dev dwarves -y

      - name: Enable drivers for anbox
        run: |
          cp Microsoft/config-wsl .config
          echo CONFIG_EROFS_FS=y >> .config

      - name: Build linux kernel
        run: make

      - uses: actions/upload-artifact@v2
        with:
          path: arch/x86/boot/bzImage
