name: Make Mesa
on: 
  push:
  workflow_dispatch:

jobs:
  makepkg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: docker://archlinux:base-devel
        with:
          entrypoint: /bin/bash
          args: /github/workspace/entrypoint.sh

      - uses: actions/upload-artifact@v2
        with:
          path: |
            mesa/trunk/*.pkg.tar.zst
