name: Android Release CI

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Decode Keystore
      run: |
        mkdir -p ~/.android
        echo "${{ secrets.SIGN_KEY }}" | base64 --decode > ~/.android/debug.keystore

    - name: Build Release
      run: ./gradlew assembleUniversalRelease

    - run: |
        cd app/build/outputs/apk/universal/release/
        mv app-universal-release.apk ReVancedXposed-${{ github.ref_name }}.apk
        gh release create --prerelease ${{ github.ref_name }} ReVancedXposed-${{ github.ref_name }}.apk
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
